# Generated by Django 3.0.5 on 2020-04-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('R', 'Running'), ('C', 'Completed'), ('U', 'Upcoming'), ('P', 'Postpont')], default='C', max_length=2),
        ),
    ]
