# Generated by Django 3.0.5 on 2020-04-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance', '0002_site_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitiondetail',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
