# Generated by Django 3.0.5 on 2020-04-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance', '0004_auto_20200418_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('R', 'Running'), ('C', 'Completed'), ('U', 'Upcoming'), ('P', 'Postpone')], default='C', max_length=2),
        ),
    ]
