# Generated by Django 3.0.5 on 2020-04-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advance', '0005_auto_20200419_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='team',
        ),
    ]
