# Generated by Django 3.0.5 on 2020-04-19 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advance', '0006_remove_requisition_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='team',
            field=models.ManyToManyField(related_name='team', to=settings.AUTH_USER_MODEL),
        ),
    ]
