# Generated by Django 3.0.5 on 2020-04-19 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advance', '0008_author_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='team',
            field=models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
